# Generated by Django 3.2.5 on 2021-07-30 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0002_rename_slug_hero_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
    ]
