# Generated by Django 3.2.5 on 2021-08-02 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0004_hero_updated_at'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='hero',
            index=models.Index(fields=['alias'], name='heroes_hero_alias_8650c5_idx'),
        ),
    ]
